# Microservices Architecture

MA: "" {
  grid-columns: 2
  #grid-rows: 2

  Mobile: "" {
    shape: image
    icon: https://icons.terrastruct.com/aws%2F_General%2FMobile-client_light-bg.svg
  }

  Home: "" {
    shape: image
    icon: https://icons.terrastruct.com/tech%2Fbrowser-2.svg
  }
  """
  UI: User Interface {
    # width: 400
    style.stroke-width: 0
    style.fill: transparent
    style.font-size: 20
    style.opacity: 0.5
  }
  """
  style.stroke-dash: 3
  style.border-radius: 8
  style.opacity: 0.5
  vertical-gap: 25
}

# style.stroke-dash: 3
# style.border-radius: 8
# near: top-center

API: API Gateway {
  style.border-radius: 8
  style.font-size: 20
}

Service A: {
  style.border-radius: 8
}

Service B: {
  style.border-radius: 8
}

Service C: {
  style.border-radius: 8
}

DB A: "" {
  shape: cylinder
  style.multiple: true
  style.stroke-width: 2
  style.opacity: 0.9
}

DB B: "" {
  shape: cylinder
  style.multiple: true
  style.stroke-width: 2
  style.opacity: 0.9
}

DB C: "" {
  shape: cylinder
  style.multiple: true
  style.stroke-width: 2
  style.opacity: 0.9
}

MA -> API # { style.animated: true }

API -> Service A
API -> Service B
API -> Service C

Service A -> DB A
Service B -> DB B
Service C -> DB C
